---
- name: Build docker image & deploy on docker container
  gather_facts: true
  hosts: localhost
  tasks:
    - name: Stop the container, if running
      ignore_errors: yes
      docker_container:
       name: ABCtechnology
       image: arunbuee/abc-technology:latest
       state: stopped
    - name: Remove container
      ignore_errors: yes
      docker_container:
       name: ABCtechnology
       image: arunbuee/abc-technology:latest
       state: absent
    - name: Remove image
      ignore_errors: yes
      docker_image:
       state: absent
       name: arunbuee/abc-technology
       tag: latest
    - name: Build the image on local
      connection: local
      docker_image:
       name: arunbuee/abc-technology
       source: build
       build:
        path: .
       tag: lates

